name: docker

on:
  push:
    branches:
    - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        flavor: latest=true
        images: sacbase/sac-jupyter-notebook
        tags: type=sha
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
