name: docker

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * 6'

jobs:
  compiler:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/metadata-action@v5
      id: meta
      with:
        flavor: latest=true
        images: sacbase/sac-compiler
        tags: type=sha
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        file: "Dockerfile.compiler"

  jupyter:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/metadata-action@v5
      id: meta
      with:
        flavor: latest=true
        images: sacbase/sac-jupyter-notebook
        tags: type=sha
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        file: "Dockerfile.jupyter"
